import { Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { useAppDispatch, useAppSelector } from '../store/hooks';
import { logout, setCredentials } from '../features/auth/authSlice';
import { authApi, useLoginMutation, useRegisterMutation } from '../features/auth/authApi';
import { CategoriesPage } from '../features/catalog/CategoriesPage';
import { useState } from 'react';

function Shell({ children }: { children: React.ReactNode }) { const dispatch = useAppDispatch(); const user = useAppSelector((s) => s.auth.user); const signOut = () => { dispatch(logout()); dispatch(authApi.util.resetApiState()); }; return <main><nav><strong>ATELIER / COMMERCE</strong><span><Link to="/">Home</Link> <Link to="/products">Products</Link> <Link to="/categories">Categories</Link> {user ? <><Link to="/profile">Profile</Link><button onClick={signOut}>Log out</button></> : <Link to="/login">Sign in</Link>}</span></nav>{children}</main>; }
function Home() { return <section className="hero"><p className="eyebrow">Student commerce platform</p><h1>Build the store<br />feature by feature.</h1><p>A vertical-slice starter for five people learning to ship production-style commerce.</p><Link className="button" to="/products">Browse catalog</Link></section>; }
function Products() { return <section className="content"><p className="eyebrow">Catalog</p><h2>Products</h2><p>The product catalog is the next vertical feature ticket.</p></section>; }
function Placeholder({ name }: { name: string }) { return <section className="content"><p className="eyebrow">Customer / {name}</p><h2>{name}</h2><p>This page is a foundation for the corresponding vertical feature ticket.</p></section>; }
function AuthPage({ register }: { register: boolean }) { const [form, setForm] = useState({ firstName: '', lastName: '', email: '', password: '' }); const [login] = useLoginMutation(); const [registerUser] = useRegisterMutation(); const dispatch = useAppDispatch(); const navigate = useNavigate(); const submit = async (event: React.FormEvent) => { event.preventDefault(); const result = register ? await registerUser(form).unwrap() : await login({ email: form.email, password: form.password }).unwrap(); dispatch(setCredentials(result)); navigate('/profile'); }; return <section className="form"><p className="eyebrow">Account</p><h2>{register ? 'Create your account' : 'Welcome back'}</h2><form onSubmit={submit}>{register && <><input placeholder="First name" required value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })} /><input placeholder="Last name" required value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })} /></>}<input type="email" placeholder="Email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><input type="password" placeholder="Password" required minLength={8} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><button className="button">{register ? 'Register' : 'Sign in'}</button></form></section>; }
function Profile() { const user = useAppSelector((s) => s.auth.user); if (!user) return <Navigate to="/login" replace />; return <section className="content"><p className="eyebrow">Authenticated</p><h2>{user.firstName} {user.lastName}</h2><p>{user.email} · {user.role}</p></section>; }
export function App() { return <Shell><Routes><Route path="/" element={<Home />} /><Route path="/products" element={<Products />} /><Route path="/products/:id" element={<Placeholder name="Product details" />} /><Route path="/categories" element={<CategoriesPage />} /><Route path="/cart" element={<Placeholder name="Cart" />} /><Route path="/checkout" element={<Placeholder name="Checkout" />} /><Route path="/orders" element={<Placeholder name="Orders" />} /><Route path="/login" element={<AuthPage register={false} />} /><Route path="/register" element={<AuthPage register />} /><Route path="/profile" element={<Profile />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></Shell>; }
